# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shoppingList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shoppingList
  pod 'Firebase/Core'
  pod 'CoreDataManager', '~> 0.8.1'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'shoppingListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shoppingListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
